# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/loongson/exp6/soc_verify/soc_dram/run_vivado/constraints/soc_lite_top.xdc

# IP: C:/Projects/loongson/exp6/soc_verify/soc_dram/rtl/xilinx_ip/data_ram/data_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet
