# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/loongson/exp3/exp3.srcs/sources_1/ip/distributed_ram/distributed_ram.xci
# IP: The module: 'distributed_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/loongson/exp3/exp3.gen/sources_1/ip/distributed_ram/distributed_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'distributed_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Projects/loongson/exp3/exp3.srcs/sources_1/ip/distributed_ram/distributed_ram.xci
# IP: The module: 'distributed_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/loongson/exp3/exp3.gen/sources_1/ip/distributed_ram/distributed_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'distributed_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
