# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/loongson/exp10/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/div_w_gen/div_w_gen.xci
# IP: The module: 'div_w_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/loongson/exp10/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_w_gen/div_w_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_w_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Projects/loongson/exp10/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/div_w_gen/div_w_gen.xci
# IP: The module: 'div_w_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/loongson/exp10/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_w_gen/div_w_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_w_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
